version: "3.8"

x-default-app:
  &default-app
  build:
    dockerfile: ./infra/Dockerfile
    target: dev
  volumes:
    - .:/code
  stdin_open: true
  tty: true

services:
  fastapi:
    <<: *default-app
    ports:
      - 8000:8000

  postgres:
    image: "postgres:15-alpine"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=esorcerer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  celery-worker:
    <<: *default-app
    command: celery --app esorcerer.plugins.tasks.worker.celery_app worker --loglevel=info
    depends_on:
      - fastapi
      - redis

  celery-beat:
    <<: *default-app
    command: celery --app esorcerer.plugins.tasks.worker.celery_app beat --loglevel=info
    depends_on:
      - fastapi
      - celery-worker
      - redis

  celery-flower:
    <<: *default-app
    command: celery --app esorcerer.plugins.tasks.worker.celery_app flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - fastapi
      - celery-worker
      - redis

volumes:
  postgres_data: {}
