version: "3.8"

services:
  fastapi:
    build:
      dockerfile: ./infra/Dockerfile
      target: dev
    volumes:
      - .:/code
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

  postgres:
    image: "postgres:15-alpine"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=esorcerer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres_data: {}
