[tool.ruff]
line-length = 90
select = ["E", "F", "I", "D", "UP", "N", "S", "C", "B"]
ignore = ["D100", "D106", "D107", "D203", "D213", "B008"]

[tool.ruff.per-file-ignores]
"test_*.py" = ["S101", "S105"]

[tool.pytest.ini_options]
pythonpath = "esorcerer"
testpaths = "tests"
asyncio_mode = "strict"
addopts = "-s --strict-markers -vv --cache-clear --maxfail=1 --cov=esorcerer --cov-report=term --cov-report=html --cov-branch --no-cov-on-fail --cov-fail-under=80 -W ignore::DeprecationWarning"
