name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Lint and test
    runs-on: ubuntu-20.04
    env:
      DEBUG: True
      REDIS_URL: redis://localhost:6379/0
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Load pip cache
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements/*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r ./requirements/local.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Load pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit hooks
        run: make lint

      - name: Run tests with pytest
        run: make test
